version: '3'
services:
  web:
    volumes:
      - ./webapp:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=8000'
